version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mondodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dima
      - MONGO_INITDB_ROOT_PASSWORD=test123
      - MONGO_INITDB_DATABASE=soulgram-interests
    volumes:
      - data01:/mongo-volume:/data/db
    ports:
      - 27017-27019:27017-27019    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dima
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test123
      - ME_CONFIG_MONGODB_URL=mongodb://dima:test123@mongo:27017/
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1111
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: 'http://es01:9200'
    networks:
      - elastic
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - SA_PASSWORD=test123#TTT
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5434:1433"

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
